### ISSUE TITLE
 IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by Prayag22** [adityap27/face-mask-detector#5]
Hello Sir,Please can you resolve this error.
Traceback (most recent call last):
  File "D:\face-mask-detector\mask-detector-video.py", line 55, in <module>
    ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "D:\face-mask-detector\mask-detector-video.py", line 55, in <listcomp>
    ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.
Thank you for helping.

**Comment by adityap27** [comment]
Please follow these steps: https://github.com/adityap27/face-mask-detector#quick-start

You might be missing some step.
